export const GET_ITEM_PENDING = 'GET_ITEM';
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS';
export const GET_ITEM_FAILURE = 'GET_ITEM_FAILURE';
export const GET_ITEM_FULFILL = 'GET_ITEM_FULFILL'

export const ADD_ITEM_PENDING = 'ADD_ITEM_PENDING';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE';
export const ADD_ITEM_FULFILL = 'ADD_ITEM_FULFILL';

export const DELETE_ITEM_PENDING = 'DELETE_ITEM_PENDING';
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
export const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';
export const DELETE_ITEM_FULFILL = 'DELETE_ITEM_FULFILL';

export const UPDATE_ITEM_PENDING = 'UPDATE_ITEM_PENDING';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE';
export const UPDATE_ITEM_FULFILL = 'UPDATE_ITEM_FULFILL';
