export const GET_BOOK_PENDING = 'GET_BOOK_PENDING';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAILURE = 'GET_BOOK_FAILURE';
export const GET_BOOK_FULFILL = 'GET_BOOK_FULFILL';

export const ADD_BOOK_PENDING = 'ADD_BOOK_PENDING';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE';
export const ADD_BOOK_FULFILL = 'ADD_BOOK_FULFILL';

export const DELETE_BOOK_PENDING = 'DELETE_BOOK_PENDING';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAILURE = 'DELETE_BOOK_FAILURE';
export const DELETE_BOOK_FULFILL = 'DELETE_BOOK_FULFILL';

export const UPDATE_BOOK_PENDING = 'UPDATE_BOOK_PENDING';
export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';
export const UPDATE_BOOK_FAILURE = 'UPDATE_BOOK_FAILURE';
export const UPDATE_BOOK_FULFILL = 'UPDATE_BOOK_FULFILL';
